apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: default
  labels:
    app: nginx
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 25%
    type: RollingUpdate
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.15.4
        resources:
          limits:
            cpu: "6"
            memory: 1000Mi
          requests:
            cpu: "6"
            memory: 1000Mi # 单位可以是 Mi Gi
        ports:
        - containerPort: 80
