apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: default
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: nginx
        image: nginx:1.15.4
        resources:
          limits:
            cpu: "3.5"
            memory: 2000Mi
          requests:
            cpu: "0.1"
            memory: 200Mi # 单位可以是 Mi Gi
        ports:
        - containerPort: 80
