apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: default
  labels:
    app: app
spec:
  replicas: 10
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 25%
    type: RollingUpdate
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: nginx
        image: nginx:1.15.4
        resources:
          limits:
            cpu: "6"
            memory: 1000Mi
          requests:
            cpu: "6"
            memory: 1000Mi # 单位可以是 Mi Gi
        ports:
        - containerPort: 80
